export const aboutContent = {
  en: {
    title: "About Us | 10 Claws",
    description: "We build complete software and practical AI tools that help industries improve how they work.",
    label: "About us",
    heading: "Turning AI into software industries can use.",
    intro: "We are 10 Claws. We build complete software products and focused tools that help industries benefit from AI in their everyday work.",
    mission: "Built around real work.",
    missionBody: "Our starting point is the work people need to get done: the repetitive tasks, disconnected information, and slow processes that hold teams back. We turn those needs into useful software, with AI applied where it can make a meaningful difference.",
    offerings: [
      { title: "Complete software", body: "End-to-end products built around an industry's workflows, bringing the interfaces, data, and AI capabilities together in one usable system." },
      { title: "Focused AI tools", body: "Purpose-built tools that help teams automate repetitive tasks, find useful information, and make better-informed decisions within their existing workflows." },
    ],
    approach: "From an industry need to a working product.",
    steps: [
      { title: "Understand the work", body: "Start with the people, processes, and problems specific to the industry." },
      { title: "Build what helps", body: "Choose the right scope, whether that is a complete product or a tool for one important task." },
      { title: "Learn and improve", body: "Use feedback from real workflows to refine the software and assess whether it saves time, reduces effort, or improves results." },
    ],
    ctaTitle: "Put AI to work in your industry.",
    ctaBody: "Have a workflow that could work better? Let's explore what we can build.",
    contact: "Send message",
    form: {
      name: "Name",
      email: "Email",
      company: "Company or industry (optional)",
      message: "What would you like to build or improve?",
      captcha: "After you press Send message, complete the CAPTCHA to submit your enquiry.",
    },
    projects: "Explore our projects",
    home: "Back to home",
  },
  ar: {
    title: "من نحن | 10 Claws",
    description: "نبني حلولاً برمجية متكاملة وأدوات عملية بالذكاء الاصطناعي تساعد القطاعات على تحسين طريقة عملها.",
    label: "من نحن",
    heading: "نحوّل الذكاء الاصطناعي إلى برمجيات تخدم القطاعات.",
    intro: "نحن 10 Claws. نبني منتجات برمجية متكاملة وأدوات متخصصة تساعد مختلف القطاعات على الاستفادة من الذكاء الاصطناعي في عملها اليومي.",
    mission: "نبدأ من احتياجات العمل الفعلية.",
    missionBody: "ننطلق من المهام التي يحتاج الناس إلى إنجازها: الأعمال المتكررة، والمعلومات المتفرقة، والإجراءات البطيئة التي تعيق الفرق. نحوّل هذه الاحتياجات إلى برمجيات مفيدة، ونوظّف الذكاء الاصطناعي حيث يمكنه إحداث فرق ملموس.",
    offerings: [
      { title: "برمجيات متكاملة", body: "منتجات تُبنى حول سير العمل في كل قطاع، وتجمع الواجهات والبيانات وقدرات الذكاء الاصطناعي في نظام واحد قابل للاستخدام." },
      { title: "أدوات ذكاء اصطناعي متخصصة", body: "أدوات مصممة لمهام محددة، تساعد الفرق على أتمتة الأعمال المتكررة، والوصول إلى المعلومات المفيدة، واتخاذ قرارات مدروسة ضمن سير عملها الحالي." },
    ],
    approach: "من احتياج في القطاع إلى منتج يعمل.",
    steps: [
      { title: "نفهم طبيعة العمل", body: "نبدأ بالأشخاص والإجراءات والمشكلات الخاصة بكل قطاع." },
      { title: "نبني ما يفيد", body: "نحدد النطاق المناسب، سواء كان منتجاً متكاملاً أو أداة لإنجاز مهمة مهمة." },
      { title: "نتعلّم ونحسّن", body: "نستفيد من الملاحظات أثناء الاستخدام الفعلي لتطوير البرمجيات وتقييم قدرتها على توفير الوقت وتقليل الجهد وتحسين النتائج." },
    ],
    ctaTitle: "وظّف الذكاء الاصطناعي في خدمة قطاعك.",
    ctaBody: "لديك سير عمل يمكن تحسينه؟ لنتحدث عمّا يمكننا بناؤه معاً.",
    contact: "إرسال الرسالة",
    form: {
      name: "الاسم",
      email: "البريد الإلكتروني",
      company: "الشركة أو القطاع (اختياري)",
      message: "ما الذي ترغب في بنائه أو تحسينه؟",
      captcha: "بعد الضغط على إرسال الرسالة، أكمل اختبار التحقق لإرسال استفسارك.",
    },
    projects: "استكشف مشاريعنا",
    home: "العودة إلى الرئيسية",
  },
}
